### ISSUE TITLE
Create controlled vocabulary

### ISSUE THREAD

**Issue by Maartenvm** [eWaterCycle/Controlled-Vocabulary#1]
- [ ] #3 Create overview of existing vocabularies
- [ ] #4 Create use cases for controlled vocabularies in eWatercycleII framework
- [ ] #5 Discuss feasibility of vocabulary alignment
- [ ] #6 Write paper on vocabulary survey for eWatercycleII
- [ ] #2 DB of keywords etc. for visualization
